### ISSUE TITLE
请适配不同环境和不同路径

### ISSUE THREAD

**Issue by yjiawqgj** [Mythologyli/transmission-to-qbittorrent#1]
我tramsmission是安装在synology上的，下载的文件，放在一个/volume1/pt/1和/volume1/pt/2、/volume1/pt/3/4这种目录下，我在DOCEKER部署了一个容器，需要transmission转移到qbittorrent，这种该工具无法实现。请适配目录匹配功能

**Comment by Mythologyli** [comment]
为何无法实现？

**Comment by yjiawqgj** [comment]
> 为何无法实现？
你这个能自动查找分级目录呀！我以为不能所以就没敢试，怕给我全弄崩了！

**Comment by yjiawqgj** [comment]
> 为何无法实现？

root@DS920:~/trtoqb# python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import qbittorrentapi
  File "/root/trtoqb/qbittorrentapi/__init__.py", line 2, in <module>
    from qbittorrentapi.app import AppAPIMixIn
  File "/root/trtoqb/qbittorrentapi/app.py", line 4, in <module>
    from qbittorrentapi.auth import AuthAPIMixIn
  File "/root/trtoqb/qbittorrentapi/auth.py", line 5, in <module>
    from qbittorrentapi.definitions import APINames
  File "/root/trtoqb/qbittorrentapi/definitions.py", line 8, in <module>
    from qbittorrentapi._attrdict import AttrDict
  File "/root/trtoqb/qbittorrentapi/_attrdict.py", line 44, in <module>
    from six import add_metaclass as six_add_metaclass
ModuleNotFoundError: No module named 'six'
root@DS920:~/trtoqb# python3 main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import qbittorrentapi
  File "/root/trtoqb/qbittorrentapi/__init__.py", line 2, in <module>
    from qbittorrentapi.app import AppAPIMixIn
  File "/root/trtoqb/qbittorrentapi/app.py", line 4, in <module>
    from qbittorrentapi.auth import AuthAPIMixIn
  File "/root/trtoqb/qbittorrentapi/auth.py", line 5, in <module>
    from qbittorrentapi.definitions import APINames
  File "/root/trtoqb/qbittorrentapi/definitions.py", line 8, in <module>
    from qbittorrentapi._attrdict import AttrDict
  File "/root/trtoqb/qbittorrentapi/_attrdict.py", line 44, in <module>
    from six import add_metaclass as six_add_metaclass
ModuleNotFoundError: No module named 'six'

json内容
{
    "skip_check": false,
    "qbittorrent": {
        "host": "10.10.10.5",
        "port": 8080,
        "username": "admin",
        "password": "adminadmin"
    },
    "transmission": {
        "protocol": "http",
        "host": "127.0.0.1",
        "port": 9091,
        "path": "/transmission/",
        "username": "xiaolulu",
        "password": "Bdmovie128126",
        "torrent_dir": "/volume1/@appdata/transmission/torrents/"
    }
}

**Comment by Mythologyli** [comment]
`pip3 install six`

**Comment by yjiawqgj** [comment]
> `pip3 install six`

root@DS920:~/trtoqb# python main.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1295, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1341, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1290, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1046, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 986, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9f525914f0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.10.10.5', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f525914f0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/trtoqb/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/root/trtoqb/qbittorrentapi/request.py", line 452, in _request
    response = self._session.request(
  File "/root/trtoqb/qbittorrentapi/request.py", line 562, in request
    return super(QbittorrentSession, self).request(method, url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.10.10.5', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f525914f0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 95, in <module>
    main()
  File "main.py", line 42, in main
    qb_client.auth_log_in()
  File "/root/trtoqb/qbittorrentapi/auth.py", line 96, in auth_log_in
    self._post(_name=APINames.Authorization, _method="login", data=creds, **kwargs)
  File "/root/trtoqb/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/root/trtoqb/qbittorrentapi/request.py", line 411, in _request_manager
    raise APIConnectionError(error_message, response=response)
qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='10.10.10.5', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9f525914f0>: Failed to establish a new connection: [Errno 113] No route to host'))"))

**Comment by Mythologyli** [comment]
`[Errno 113] No route to host`
无法登录 qbittorrent

**Comment by yjiawqgj** [comment]
> `[Errno 113] No route to host` 无法登录 qbittorrent

![image](https://github.com/Mythologyli/transmission-to-qbittorrent/assets/71002956/a391c61b-7cdc-4c6e-b991-25634d04506f)
能登陆呀！

**Comment by yjiawqgj** [comment]
> `[Errno 113] No route to host` 无法登录 qbittorrent

已经排除故障了，但是你这还是不行，TR套件版下载地址为/volume2/PT,容器qb下载地址为/downloads,虽然我已经做了映射，/volume2/PT:/downloads,转移过去下地地址还是/volume2/PT开头的地址。这怎么能用？!!

**Comment by Mythologyli** [comment]
README 中明确写着**还需确保所有种子的下载路径在两个 Docker 容器中的对应路径相同，即将宿主机同一文件夹挂载到两个 Docker 容器的相同目录中**。你自己映射的在容器里的路径我的程序怎么可能知道？我的程序怎么可能未卜先知地猜出你需要的地址？你只能在容器中建立 `/volume2/PT` 然后映射 `/volume2/PT:/volume2/PT`，不然你就只能自己去改代码让程序知道下载目录是什么。
另外麻烦语气好一点，没人求着你用
